server:
  port: 1898

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: service-all
    description: Foxnic Web Service All
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    druid:
      primary:
        encrypt:
          enable: true
          file:
            windows: d:/foxnic/passwd.txt
            mac: /Users/Shared/foxnic/passwd.txt
            linux: /foxnic/passwd.txt
        # db-1
        url: ai+mCm8asbK9SNrQDk7ac29neidjdgHp2jFU7HYbZZM7XPIVnc3jn040SCi2ghsOJmvzo7Z8DsMWz0GJtHzk5fVkSVq8PVTLpt97W7e4//KN1tJ8luj3f2R4xGk6d01pnyaG7DyU2tsIMcGZTOl8T0kLJom6Izu9ePptW1UPa7MuTPWKDKUSCYKdQSv51ASxJE99hLodGgxEtGeRBhnlDigwekNCLkMQGvjVKTeDRDsro2ghN1qDTzmyCaGJQxMq
        username: tD5wkJAfnCt04A+Y+QN5GA==
        password: ODGx5F84xpWJgfRFnzAaYhViHJqrTO3uxxDZ2lRlZNk=
        # db-2
        #url: ai+mCm8asbK9SNrQDk7acwFudx/85JSmGG0oO6UIbEQuHyAECjhpYNu498VsI+yuzMJGjNdFWmZBFeX1CBxN/JCMveiHfB5RycbYXosZS2zowedyYWd66RDP6lRhDjg8uDRtWUDh6WEHC5jVLjUaEr94jv61Uh7brCMbsQbY3ihNAcM79lGwTfV3of3ALwDHSEyVtgHG6PMpk+u00M7B6nRY9KzXnzkCErTbNtU2GaGcYi+ey3SpL9kQx7eGv7Fy
        #username: IJ4ZT+NqsHTkfq9MMjSAxw==
        #password: WwvxnxIYA86yquXUpqrVFw==

        #        driver-class-name: dm.jdbc.driver.DmDriver
        #        url: sI2+hq2vWmNtpey9cP6SoymBrYAzdXtCIvGGIofc5SGKCQylHa3KjkVCCXiSiE8E
        #        username: dG0gpFrfyei8IXOBJa4QJQ==
        #        password: Gds7qlZU6Q9MW84y/ONk9Q==
        min-idle: 1
        initial-size: 2
        max-active: 64
        max-wait: 60000
        printSQL: true


security:
  # 模式：session / jwt
  mode: jwt
  # 配置无需鉴权可以访问的地址
  ignored-urls: /error
  # mode=jwt 时配置的 jwt 选项
  jwt:
    key-location: felordcn.jks
    key-alias: felordcn
    key-pass: 123456
    # 缓存类型  local/remote/both
    cache-type: local
    iss: felord.cn
    sub: all
    access-expire-seconds: 20
    refresh-expire-seconds: 30


logging:
  config: classpath:logback-config.xml

snowflake:
  datacenterId: 1
  workerId: 1

management:
  endpoints:
    web:
      exposure:
        include: "*"

knife4j:
  enable: true
  title: ${spring.application.name}
  description: ${spring.application.description}
  version: 1.0

upload:
  windows: c:/upload
  mac: /Users/LeeFJ/git/tailoring/uploads
  linux: /tailoring/uploads
