ALTER TABLE `act_hi_actinst`
    MODIFY COLUMN `ASSIGNEE_` varchar(1024) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL;

ALTER TABLE `act_hi_taskinst`
    MODIFY COLUMN `ASSIGNEE_` varchar(1024) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL;

ALTER TABLE `eam`.`act_ru_task`
    MODIFY COLUMN `ASSIGNEE_` varchar(1024) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL AFTER `OWNER_`;
