
settings:
  enableMicroService: true 
  enableSwagger: true


#源代码相关的部分
source: 
  #DAO常量名
  daoNameConst: org.github.foxnic.web.framework.dao.DBConfigs.PRIMARY_DAO
  #系统常量包名
  domainConstantsPackage: org.github.foxnic.web.constants

#使用不同的机器码对应到作者
authors:
  #指定机器码与对应的作者，机器码在代码生成时控制台输出，或main函数调用 Machine.getIdentity()
  B15BDA59450483F9: 李方捷 , leefangjie@qq.com
  B1894FFE47E36B09: 李方捷 , leefangjie@qq.com
  D11C00DED5F5C932: 金杰 , maillank@qq.com


compoments: 
  domain: /common/domain
  proxy: /common/proxy
  


#应用清单
applications: 
  #系统服务
  service-system:  
    nacosGroup: service
    nacosDataId: service-system.yml
    serviceProjectPath:  /service/service-system
    packageName: org.github.foxnic.web.system
    primaryDatasourceConfigKey: spring.datasource.druid.primary
    microServiceNameConst: SYSTEM
    viewProjectPath: /view/view-console
    viewPrefixPath: public/business/system
    wrapperProjectPath:  /wrapper/wrapper-service-system
  #存储服务
  service-storage:  
    nacosGroup: service
    nacosDataId: service-storage.yml
    serviceProjectPath:  /service/service-storage
    packageName: org.github.foxnic.web.storage
    primaryDatasourceConfigKey: spring.datasource.druid.primary
    microServiceNameConst: STORAGE
    viewProjectPath: /view/view-console
    viewPrefixPath: public/business/storage
    wrapperProjectPath:  /wrapper/wrapper-all-service
  #存储服务
  service-oauth:  
    nacosGroup: service
    nacosDataId: service-oauth.yml
    serviceProjectPath:  /service/service-oauth
    packageName: org.github.foxnic.web.oauth
    primaryDatasourceConfigKey: spring.datasource.druid.primary
    microServiceNameConst: OAUTH
    viewProjectPath: /view/view-console
    viewPrefixPath: public/business/oauth
    wrapperProjectPath:  /wrapper/wrapper-service-oauth
  #HRM
  service-hrm:
    nacosGroup: service
    nacosDataId: service-hrm.yml
    serviceProjectPath:  /service/service-hrm
    packageName: org.github.foxnic.web.hrm
    primaryDatasourceConfigKey: spring.datasource.druid.primary
    microServiceNameConst: HRM
    viewProjectPath: /view/view-console
    viewPrefixPath: public/business/hrm
    wrapperProjectPath:  /wrapper/wrapper-all-service
  #PCM  属性自定义服务
  service-pcm:
    nacosGroup: service
    nacosDataId: service-pcm.yml
    serviceProjectPath: /service/service-pcm
    packageName: org.github.foxnic.web.pcm
    primaryDatasourceConfigKey: spring.datasource.druid.primary
    microServiceNameConst: PCM
    viewProjectPath: /view/view-console
    viewPrefixPath: public/business/pcm
    wrapperProjectPath:  /wrapper/wrapper-all-service
