spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    druid:
      primary:
        encrypt:
          enable: true
          file:
            windows: d:/foxnic/passwd.txt
            mac: /Users/Shared/foxnic/passwd.txt
            linux: /foxnic/passwd.txt
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: ggdlOOBMie3vE8HByRqs+BgUVl6hx82mm7MvCATepLnLyfrv38EeIWdtheCT15s9ZFxardNYEjXZRNf9VGmxy6VzfkOzLPRJMv4cbXMD8m5RZtAt5flc/PfNB2ScolLZ9htpur58Y4AMzJD3ma0pJA8m9Mild+AG93Lnbn72yoA6SAENEhP27C0vXcDnMBzPLLNhgZSZ0mT8b92Yc3X0xqzKbPcXfg2XdJy84evH+qw04hjuX9RtsLEmjLX6QRHH
        username: tD5wkJAfnCt04A+Y+QN5GA==
        password: ODGx5F84xpWJgfRFnzAaYhViHJqrTO3uxxDZ2lRlZNk=
        min-idle: 1
        initial-size: 2
        max-active: 64
        max-wait: 60000
        printSQL: true


logging:
  config: classpath:logback-config.xml

snowflake:
  datacenterId: 1
  workerId: 1

management:
  endpoints:
    web:
      exposure:
        include: "*"

knife4j:
  enable: true
  title: ${spring.application.name}
  description: ${spring.application.description}
  version: 1.0

upload:
  windows: c:/upload
  mac: /Users/LeeFJ/git/tailoring/uploads
  linux: /tailoring/uploads
