server:
  session: 
    timeout: 20
  port: 1899
 
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: service-all
    description: Foxnic Web Service All
  servlet: 
    multipart: 
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    druid:
      primary:
        driver-class-name: com.mysql.cj.jdbc.Driver
        #url: jdbc:mysql://39.105.191.22:3306/eam?useSSL=false&serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowPublicKeyRetrieval=true&tinyInt1isBit=false
        #username: root
        #password: root_pwd
        url: jdbc:mysql://47.92.240.43:3306/foxnic-web?useSSL=false&serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowPublicKeyRetrieval=true&tinyInt1isBit=false
        username: tailoring
        password: Tailoring@2021
        min-idle: 1
        initial-size: 2
        max-active: 64
        max-wait: 60000
        printSQL: true
  thymeleaf:
    prefix: classpath:/public/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5
    cache: false



security: 
  #会话时长，单位秒
  sessionTime : 1200
  sessionCacheType: local
  ignored: /assets/** , /pages/tpl/** , /favicon.ico , /module/** ,  /**/*.css , /**/*.js
  loginPage: /login.html

# jwt
jwt:
  config:
    enabled: true
    key-location: felordcn.jks
    key-alias: felordcn
    key-pass: 123456
    iss: felord.cn
    sub: all
    access-exp-days: 30
    refresh-exp-days: 90


logging:
  config: classpath:logback-config.xml  

snowflake: 
  datacenterId: 1  
  workerId: 1

management:
  endpoints:
    web:
      exposure:
        include: "*"  

knife4j: 
  enable: true
  title: ${spring.application.name}
  description: ${spring.application.description}
  version: 1.0        

upload: 
  windows: c:/upload
  mac: /Users/LeeFJ/git/tailoring/uploads
  linux: /tailoring/uploads         